version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: catalogo_jogos
    volumes:
      - ./database/catalogo_jogos_dump.sql:/docker-entrypoint-initdb.d/dump.sql

  api:
    build: .                   
    container_name: catalogo_api
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=catalogo_jogos;Uid=root;Pwd=123;
    ports:
      - "8080:8080"
    restart: unless-stopped
